HEADERS = ["Uзи, В", "Uси, В"] + ["9", "8", "7", "6", "5", "4", "3", "2", "1", "0.5", "0.2", "0.1"]
TABLE_ROW_COUNT = 6
TABLE_COLUMN_COUNT = len(HEADERS)

ROW_NUMBER_ONE = 0
ROW_NUMBER_SIX = 5

COLUMN_NUMBER_ONE = 0
START_COLUMN = 2

THRESHOLD = 1e-3
THRESHOLD_DELTA_U = 1e-9
THRESHOLD_DELTA_I = 1e-9

V_OHM_LOW = 0.1
V_OHM_HIGH = 0.5
V_DYN_LOW = 6.0
V_DYN_HIGH = 9.0

MIN_POINTS_TO_SHOW_PLOT = 2
