TABLE_ROW_COUNT = 36
TABLE_COLUMN_COUNT = 3
TABLE_WIDTH = 350
TABLE_RESISTANCE_COLUMN_COUNT = 4
TABLE_RESISTANCE_WIDTH = 500

COLUMN_NUMBER_ONE = 0
COLUMN_NUMBER_TWO = 1
COLUMN_NUMBER_THREE = 2
COLUMN_NUMBER_FOUR = 3

I_S_SI = 3.2e-8
SI_N = 2.0
R_S_SI = 0.042
U_T = 0.0253

MIN_POINTS_TO_CALC_R_D = 2
