TABLE_AMPLITUDE_ROW_COUNT = 48
TABLE_AMPLITUDE_COLUMN_COUNT = 3
TABLE_OUTPUT_ROW_COUNT = 9
TABLE_OUTPUT_COLUMN_COUNT = 8

COLUMN_NUMBER_ONE = 0
COLUMN_NUMBER_TWO = 1
COLUMN_NUMBER_THREE = 2
COLUMN_NUMBER_FOUR = 3

ROW_NUMBER_ONE = 0
ROW_NUMBER_TWO = 1
ROW_NUMBER_THREE = 2
ROW_NUMBER_FOUR = 3
ROW_NUMBER_FIVE = 4
ROW_NUMBER_SIX = 5
ROW_NUMBER_SEVEN = 6
ROW_NUMBER_EIGHT = 7
ROW_NUMBER_NINE = 8

MIN_POINTS_TO_SHOW_PLOT = 10

MIN_POINTS_TO_CALC_STAB = 2

STAB_THRESHOLD = 0.01
