TABLE_ROW_COUNT = 46
TABLE_COLUMN_COUNT = 3
TABLE_WIDTH = 350
TABLE_RESISTANCE_COLUMN_COUNT = 4
TABLE_RESISTANCE_WIDTH = 500

COLUMN_NUMBER_ONE = 0
COLUMN_NUMBER_TWO = 1
COLUMN_NUMBER_THREE = 2
COLUMN_NUMBER_FOUR = 3

STAB_N = 1.0
U_T = 0.0253

MIN_RD_CONDITION = 5
MIN_POINTS_TO_CALC_STAB = 2
MIN_POINTS_TO_CALC_RD = 2
MIN_POINTS_TO_SHOW_PLOT = 10
